import {
  HASH_MARKER_PREFIX,
  HASH_PLACEHOLDER,
  SECTION_CUSTOM_TOKEN,
  SECTION_MARKER_PREFIX,
} from "../constants.js";

/**
 * Section marker helpers. Markers are HTML comments so they're invisible in
 * rendered markdown but trivially machine-readable by the diff engine
 * (Phase 1) and preservation logic (custom sections survive sync).
 */

export function openMarker(id: string, mode?: "custom"): string {
  const suffix = mode === "custom" ? ` ${SECTION_CUSTOM_TOKEN}` : "";
  return `<!-- ${SECTION_MARKER_PREFIX}${id}${suffix} -->`;
}

export function closeMarker(id: string): string {
  return `<!-- ${SECTION_MARKER_PREFIX}${id}:end -->`;
}

/** Wrap a section body with open/close markers. Empty body → empty output. */
export function wrapSection(id: string, content: string): string {
  if (!content) return "";
  return `${openMarker(id)}\n${content}\n${closeMarker(id)}`;
}

/** Footer with an unfilled hash slot; `stampHash` substitutes the real digest. */
export function footerWithPlaceholder(): string {
  return [
    "---",
    "<!-- Generated by Aware. Edit .aware.json and run `aware sync`. -->",
    `<!-- ${HASH_MARKER_PREFIX}${HASH_PLACEHOLDER} -->`,
  ].join("\n");
}

// Section IDs are alphanumeric plus `-` / `_` / `.` — colons are reserved for
// the `:end` suffix so open/close markers can never alias each other.
const SECTION_ID_PATTERN = "[a-zA-Z0-9_.\\-]+";
const SECTION_BLOCK_RE = new RegExp(
  `<!--\\s*${SECTION_MARKER_PREFIX}(${SECTION_ID_PATTERN})(?:\\s+(${SECTION_CUSTOM_TOKEN}))?\\s*-->` +
    `([\\s\\S]*?)` +
    `<!--\\s*${SECTION_MARKER_PREFIX}\\1:end\\s*-->`,
  "g",
);

export interface ParsedSection {
  id: string;
  custom: boolean;
  body: string;
  /** Byte offset of the open marker in the source content. */
  start: number;
  /** Byte offset just past the close marker. */
  end: number;
}

/**
 * Parse all section blocks from generated content. Used by Phase 1 to
 * localize hand-edits (diff per section) and preserve `custom` sections.
 */
export function parseSections(content: string): ParsedSection[] {
  const sections: ParsedSection[] = [];
  const re = new RegExp(SECTION_BLOCK_RE.source, "g");
  let match: RegExpExecArray | null;
  while ((match = re.exec(content)) !== null) {
    sections.push({
      id: match[1]!,
      custom: match[2] === SECTION_CUSTOM_TOKEN,
      body: (match[3] ?? "").replace(/^\n/, "").replace(/\n$/, ""),
      start: match.index,
      end: match.index + match[0].length,
    });
  }
  return sections;
}
